apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vu5hcd9zh-go
  janus-idp.io/tekton: vu5hcd9zh-go
  backstage.io/kubernetes-id: vu5hcd9zh-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vu5hcd9zh-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
